#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Feb 03 16:51:00 -05 2022
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 5e8e2d0a649a427cbe0b25a4fb3a324e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot FPGA_tb_behav xil_defaultlib.FPGA_tb -log elaborate.log"
xelab -wto 5e8e2d0a649a427cbe0b25a4fb3a324e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot FPGA_tb_behav xil_defaultlib.FPGA_tb -log elaborate.log

